# all colors are in RGB/RGBA hexadecimal.
primary = "#303446"           # background color
secondary = "#a6d189"         # header, footer, and incoming connections color
outgoing = "#f4b8e4"          # outgoing connections color
text_body = "#c6d0f5"         # body text color
text_headers = "#232634"      # header and footer text color
starred = "#e5c890aa"         # favorites' star color
